# Generated by Django 6.0.5 on 2026-09-07 19:45

from datetime import timedelta

import apps.issues.models
import django.utils.timezone
from django.db import migrations, models


def backfill_epic_activity(apps_registry, schema_editor):
    """Seed real values for existing Epics instead of leaving the blanket
    "now" default from the AddField operations above.

    - last_activity_at becomes the most recent updated_at among the Epic's own
      row and its direct Story children (matching what the new signal/bulk-view
      hooks will maintain going forward), falling back to the Epic's created_at
      if it has no Stories yet.
    - inactivity_alert_due_at becomes last_activity_at + 7 days, EXCEPT for
      Epics already in a terminal status (done/won't do/archived), which get
      NULL — a already-finished Epic must never carry a pending alert.

    This is a one-time cost paid once at migration time, not a repeating
    scheduled query, so scanning Stories here is acceptable. Deliberately does
    not import apps.issues.models (beyond the AddField default above, which
    Django's own migration framework already pins by reference) — migrations
    must stay independent of future changes to real model code, so the terminal
    statuses and grace period are hardcoded to this migration's own snapshot.
    """
    BaseIssue = apps_registry.get_model("issues", "BaseIssue")
    Epic = apps_registry.get_model("issues", "Epic")

    terminal_statuses = {"done", "wont_do", "archived"}
    grace_period = timedelta(days=7)

    for epic in Epic.objects.all().iterator(chunk_size=200):
        latest_story_activity = (
            BaseIssue.objects.filter(
                path__startswith=epic.path,
                depth=epic.depth + 1,
                polymorphic_ctype__model="story",
            )
            .order_by("-updated_at")
            .values_list("updated_at", flat=True)
            .first()
        )
        last_activity_at = max(filter(None, [epic.updated_at, latest_story_activity])) or epic.created_at

        Epic.objects.filter(pk=epic.pk).update(
            last_activity_at=last_activity_at,
            inactivity_alert_due_at=(None if epic.status in terminal_statuses else last_activity_at + grace_period),
        )


def noop_reverse(apps_registry, schema_editor):
    """Nothing to reverse: the AddField operations' RemoveField (auto-generated
    by Django on reverse) already drops both columns entirely."""


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0008_drop_milestone_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="inactivity_alert_due_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=apps.issues.models._default_inactivity_alert_due_at,
                help_text="When this epic becomes eligible for an inactivity alert, or blank if none is pending.",
                null=True,
                verbose_name="Inactivity Alert Due At",
            ),
        ),
        migrations.AddField(
            model_name="epic",
            name="last_activity_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When a Story was last added to or updated under this epic.",
                verbose_name="Last Activity At",
            ),
        ),
        migrations.RunPython(backfill_epic_activity, noop_reverse),
    ]
