# Generated by Django 6.0.5 on 2026-09-10 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_schedule_epic_inactivity_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='issues.epic', verbose_name='Epic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Epic Assignment',
                'verbose_name_plural': 'Epic Assignments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['epic'], name='issues_epic_epic_id_ec77fe_idx'), models.Index(fields=['user'], name='issues_epic_user_id_6eaf18_idx')],
                'constraints': [models.UniqueConstraint(fields=('epic', 'user'), name='unique_epic_assignee')],
            },
        ),
    ]
