# Generated by Django 6.0.5 on 2026-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_epic_inactivity',
            field=models.BooleanField(default=True, help_text='Email me when an epic assigned to me has had no story activity for a week.', verbose_name='Notify on epic inactivity'),
        ),
    ]
