# Generated by Django 6.0.5 on 2026-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_epic_inactivity_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_epic_activity',
            field=models.BooleanField(default=True, help_text='Email me when a story, bug or chore under an epic I own is created or edited.', verbose_name='Notify on epic activity'),
        ),
    ]
