# Generated by Django 6.0.5 on 2026-09-11 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_epic_activity_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(editable=False, help_text='Hash identifying one notification event for one recipient.', max_length=64, unique=True, verbose_name='Idempotency Key')),
                ('kind', models.CharField(help_text='A NotificationKind value. Stored as text so an old row survives a renamed kind.', max_length=32, verbose_name='Kind')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'kind'], name='notificatio_recipie_babd55_idx')],
            },
        ),
    ]
